"""
AEP v2 - Execution Service
AI Agent Task Execution Engine
"""

import asyncio
import json
import logging
from datetime import datetime
from typing import Dict, List, Optional, Any
from fastapi import FastAPI, WebSocket, WebSocketDisconnect, HTTPException
from fastapi.middleware.cors import CORSMiddleware
from pydantic import BaseModel
import uvicorn

# Configure logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger(__name__)

# FastAPI app
app = FastAPI(title="AEP Execution Service", version="2.0.0")

app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

# Models
class TaskInput(BaseModel):
    task_id: str
    agent_id: str
    task_type: str
    requirements: Dict[str, Any]
    context: Optional[Dict[str, Any]] = None

class ExecutionResult(BaseModel):
    execution_id: str
    task_id: str
    status: str
    output: Optional[str] = None
    cid: Optional[str] = None
    logs: List[Dict[str, Any]]
    started_at: datetime
    completed_at: Optional[datetime] = None

# In-memory storage (use Redis in production)
executions: Dict[str, Dict] = {}
active_connections: Dict[str, WebSocket] = {}

# Mock AI Agent implementations
class AIAgent:
    """Base AI Agent class"""
    
    def __init__(self, agent_id: str, capabilities: List[str]):
        self.agent_id = agent_id
        self.capabilities = capabilities
        self.status = "idle"
    
    async def execute(self, task: TaskInput, execution_id: str) -> ExecutionResult:
        """Execute a task"""
        self.status = "executing"
        logs = []
        
        try:
            # Log start
            logs.append({
                "timestamp": datetime.utcnow().isoformat(),
                "level": "info",
                "message": f"Starting execution of {task.task_type} task"
            })
            
            # Simulate execution based on task type
            if task.task_type == "text_generation":
                output = await self._generate_text(task, logs)
            elif task.task_type == "code_generation":
                output = await self._generate_code(task, logs)
            elif task.task_type == "data_analysis":
                output = await self._analyze_data(task, logs)
            else:
                output = await self._generic_execute(task, logs)
            
            # Log completion
            logs.append({
                "timestamp": datetime.utcnow().isoformat(),
                "level": "info",
                "message": "Execution completed successfully"
            })
            
            self.status = "idle"
            
            return ExecutionResult(
                execution_id=execution_id,
                task_id=task.task_id,
                status="completed",
                output=output,
                cid=f"Qm{execution_id[:44]}",  # Mock CID
                logs=logs,
                started_at=datetime.utcnow(),
                completed_at=datetime.utcnow()
            )
            
        except Exception as e:
            logger.error(f"Execution failed: {e}")
            logs.append({
                "timestamp": datetime.utcnow().isoformat(),
                "level": "error",
                "message": f"Execution failed: {str(e)}"
            })
            
            self.status = "idle"
            
            return ExecutionResult(
                execution_id=execution_id,
                task_id=task.task_id,
                status="failed",
                output=None,
                logs=logs,
                started_at=datetime.utcnow(),
                completed_at=datetime.utcnow()
            )
    
    async def _generate_text(self, task: TaskInput, logs: List[Dict]) -> str:
        """Generate text content"""
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Loading language model..."
        })
        await asyncio.sleep(1)
        
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Generating content based on requirements..."
        })
        await asyncio.sleep(2)
        
        topic = task.requirements.get("topic", "general")
        return f"""# {topic.title()} - Generated Content

This is a comprehensive piece of content about {topic}.

## Key Points

1. **Introduction**: Understanding the fundamentals of {topic}
2. **Analysis**: Deep dive into core concepts
3. **Conclusion**: Summary and next steps

Generated by Agent {self.agent_id} at {datetime.utcnow().isoformat()}
"""
    
    async def _generate_code(self, task: TaskInput, logs: List[Dict]) -> str:
        """Generate code"""
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Analyzing requirements..."
        })
        await asyncio.sleep(0.5)
        
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Generating code structure..."
        })
        await asyncio.sleep(1)
        
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Implementing functions..."
        })
        await asyncio.sleep(1.5)
        
        language = task.requirements.get("language", "python")
        
        if language == "python":
            return '''#!/usr/bin/env python3
"""
Generated Python Module
"""

class TaskExecutor:
    def __init__(self):
        self.status = "initialized"
    
    def execute(self, task_input: dict) -> dict:
        """Execute a task with the given input"""
        self.status = "executing"
        
        # Process task
        result = self._process(task_input)
        
        self.status = "completed"
        return result
    
    def _process(self, data: dict) -> dict:
        """Internal processing logic"""
        return {
            "success": True,
            "data": data,
            "timestamp": "2024-01-01T00:00:00Z"
        }

if __name__ == "__main__":
    executor = TaskExecutor()
    result = executor.execute({"test": "data"})
    print(result)
'''
        else:
            return f"// Generated {language} code\n// Implementation here\n"
    
    async def _analyze_data(self, task: TaskInput, logs: List[Dict]) -> str:
        """Analyze data"""
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Loading dataset..."
        })
        await asyncio.sleep(1)
        
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Running statistical analysis..."
        })
        await asyncio.sleep(2)
        
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": "Generating visualizations..."
        })
        await asyncio.sleep(1)
        
        return json.dumps({
            "analysis_type": "statistical",
            "sample_size": 10000,
            "mean": 42.5,
            "median": 41.0,
            "std_dev": 8.3,
            "insights": [
                "Strong positive correlation detected",
                "Outliers identified in dataset",
                "Trend shows 15% growth"
            ]
        }, indent=2)
    
    async def _generic_execute(self, task: TaskInput, logs: List[Dict]) -> str:
        """Generic task execution"""
        logs.append({
            "timestamp": datetime.utcnow().isoformat(),
            "level": "info",
            "message": f"Executing {task.task_type} task..."
        })
        await asyncio.sleep(2)
        
        return f"Task {task.task_id} completed by agent {self.agent_id}"

# Agent pool
agent_pool: Dict[str, AIAgent] = {
    "agent_001": AIAgent("agent_001", ["text_generation", "code_generation"]),
    "agent_002": AIAgent("agent_002", ["data_analysis", "research"]),
    "agent_003": AIAgent("agent_003", ["code_generation", "review"]),
}

# API Endpoints
@app.get("/health")
async def health_check():
    return {"status": "healthy", "service": "execution-service"}

@app.get("/executions")
async def list_executions(
    task_id: Optional[str] = None,
    agent_id: Optional[str] = None,
    status: Optional[str] = None
):
    """List executions with optional filters"""
    result = list(executions.values())
    
    if task_id:
        result = [e for e in result if e["task_id"] == task_id]
    if agent_id:
        result = [e for e in result if e["agent_id"] == agent_id]
    if status:
        result = [e for e in result if e["status"] == status]
    
    return {"success": True, "data": result}

@app.get("/executions/{execution_id}")
async def get_execution(execution_id: str):
    """Get execution details"""
    if execution_id not in executions:
        raise HTTPException(status_code=404, detail="Execution not found")
    
    return {"success": True, "data": executions[execution_id]}

@app.post("/executions")
async def create_execution(task: TaskInput):
    """Create and start a new execution"""
    execution_id = f"exec_{datetime.utcnow().timestamp()}"
    
    # Get agent
    agent = agent_pool.get(task.agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="Agent not found")
    
    # Create execution record
    executions[execution_id] = {
        "execution_id": execution_id,
        "task_id": task.task_id,
        "agent_id": task.agent_id,
        "status": "queued",
        "logs": [],
        "started_at": datetime.utcnow().isoformat(),
        "completed_at": None
    }
    
    # Start execution asynchronously
    asyncio.create_task(_run_execution(execution_id, task, agent))
    
    return {"success": True, "data": executions[execution_id]}

async def _run_execution(execution_id: str, task: TaskInput, agent: AIAgent):
    """Run execution in background"""
    executions[execution_id]["status"] = "running"
    
    result = await agent.execute(task, execution_id)
    
    executions[execution_id].update({
        "status": result.status,
        "output": result.output,
        "cid": result.cid,
        "logs": [log.dict() if hasattr(log, 'dict') else log for log in result.logs],
        "completed_at": result.completed_at.isoformat() if result.completed_at else None
    })

@app.post("/executions/{execution_id}/cancel")
async def cancel_execution(execution_id: str):
    """Cancel an execution"""
    if execution_id not in executions:
        raise HTTPException(status_code=404, detail="Execution not found")
    
    executions[execution_id]["status"] = "cancelled"
    
    return {"success": True, "data": executions[execution_id]}

@app.get("/executions/{execution_id}/logs")
async def get_execution_logs(execution_id: str, from_line: int = 0, limit: int = 100):
    """Get execution logs"""
    if execution_id not in executions:
        raise HTTPException(status_code=404, detail="Execution not found")
    
    logs = executions[execution_id].get("logs", [])
    return {
        "success": True,
        "data": logs[from_line:from_line + limit]
    }

# WebSocket for real-time logs
@app.websocket("/ws/executions/{execution_id}")
async def websocket_logs(websocket: WebSocket, execution_id: str):
    await websocket.accept()
    active_connections[execution_id] = websocket
    
    try:
        while True:
            # Send current logs
            if execution_id in executions:
                logs = executions[execution_id].get("logs", [])
                await websocket.send_json({
                    "type": "logs",
                    "data": logs[-10:]  # Last 10 logs
                })
            
            await asyncio.sleep(1)
            
    except WebSocketDisconnect:
        del active_connections[execution_id]

@app.get("/agents")
async def list_agents():
    """List available execution agents"""
    return {
        "success": True,
        "data": [
            {
                "agent_id": agent_id,
                "capabilities": agent.capabilities,
                "status": agent.status
            }
            for agent_id, agent in agent_pool.items()
        ]
    }

if __name__ == "__main__":
    uvicorn.run(app, host="0.0.0.0", port=3003)
